export const GET_ERRORS = "GET_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_THERAPISTS = "GET_THERAPISTS";
export const GET_THERAPIST = "GET_THERAPIST";
export const ADD_THERAPIST = "ADD_THERAPIST";
export const UPDATE_THERAPIST = "UPDATE_THERAPIST";
export const THERAPISTS_LOADING = "THERAPISTS_LOADING";


export const GET_PARENTS = "GET_PARENTS";
export const GET_PARENT = "GET_PARENT";
export const ADD_PARENT = "ADD_PARENT";
export const UPDATE_PARENT = "UPDATE_PARENT";
export const PARENTS_LOADING = "PARENTS_LOADING";

export const GET_PATIENTS = "GET_PATIENTS";
export const GET_PATIENT = "GET_PATIENT";
export const ADD_PATIENT = "ADD_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const PATIENTS_LOADING = "PATIENTS_LOADING";
export const GET_PATIENT_THERAPISTS = "GET_PATIENT_THERAPISTS";
export const ADD_THERAPIST_PATIENT = "ADD_THERAPIST_PATIENT";
export const REMOVE_THERAPIST_PATIENT = "REMOVE_THERAPIST_PATIENT";