export const GET_ERRORS = "GET_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_THERAPISTS = "GET_THERAPISTS";
export const GET_THERAPIST = "GET_THERAPIST";
export const ADD_THERAPIST = "ADD_THERAPIST";
export const UPDATE_THERAPIST = "UPDATE_THERAPIST";
export const THERAPISTS_LOADING = "THERAPISTS_LOADING";


export const GET_PARENTS = "GET_PARENTS";
export const GET_PARENT = "GET_PARENT";
export const ADD_PARENT = "ADD_PARENT";
export const UPDATE_PARENT = "UPDATE_PARENT";
export const PARENTS_LOADING = "PARENTS_LOADING";

export const GET_PATIENTS = "GET_PATIENTS";
export const GET_PATIENT = "GET_PATIENT";
export const ADD_PATIENT = "ADD_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const PATIENTS_LOADING = "PATIENTS_LOADING";

export const GET_PATIENT_THERAPISTS = "GET_PATIENT_THERAPISTS";
export const ADD_THERAPIST_PATIENT = "ADD_THERAPIST_PATIENT";
export const REMOVE_THERAPIST_PATIENT = "REMOVE_THERAPIST_PATIENT";

export const GET_PATIENT_PARENTS = "GET_PATIENT_PARENTS";
export const ADD_PARENT_PATIENT = "ADD_PARENT_PATIENT";
export const REMOVE_PARENT_PATIENT = "REMOVE_PARENT_PATIENT";

export const ADD_MEDICINE = "ADD_MEDICINE";
export const GET_MEDICINES = "GET_MEDICINES";
export const GET_MEDICINE = "GET_MEDICINE";
export const REMOVE_MEDICINE = "REMOVE_MEDICINE";
export const UPDATE_MEDICINE = "UPDATE_MEDICINE";

export const ADD_THERAPEUTIC_NOTE = "ADD_THERAPEUTIC_NOTE";
export const GET_THERAPEUTIC_NOTES = "GET_THERAPEUTIC_NOTES";
export const GET_THERAPEUTIC_NOTE = "GET_THERAPEUTIC_NOTE";
export const REMOVE_THERAPEUTIC_NOTE = "REMOVE_THERAPEUTIC_NOTE";
export const UPDATE_THERAPEUTIC_NOTE = "UPDATE_THERAPEUTIC_NOTE";

export const ADD_RESOURCE = "ADD_RESOURCE";
export const GET_RESOURCES = "GET_RESOURCES";
export const GET_RESOURCE = "GET_RESOURCE";
export const REMOVE_RESOURCE = "REMOVE_RESOURCE";
export const UPDATE_RESOURCE = "UPDATE_RESOURCE";

